site_name: C语言高级技术
theme: readthedocs
nav:
  - 引言: index.md
  - 重要概念: basic/concepts.md
  - 重要的宏: basic/macros.md
  - 面向对象: core/object_oriented.md
  - 模板（泛型）: core/template.md
  - 错误处理: core/error_handling.md
  - 使用宏实现通用vector: vector/macro_vector.md
  - 使用void*实现通用vector: vector/opaque_pointer_vector.md
  - 基础BUG: core/bugs.md
  - 测试驱动: test/test_driven.md
  - 常用编译器: tools/compiler.md
  - 构建系统: tools/build_system.md
  - 调试方法: tools/debug.md
  - 静态检查: analysis/static_check.md
  - 动态分析: analysis/dynamic_analysis.md
  - libc实现浅析: ext/libc.md
  - 自定义编译器: ext/custom_compiler.md
  